#!/bin/sh
set -e

bin_path="/opt/secureserver-agent/embedded"
bins="secureserver-agent secureserver-config"
user="secserv"

if [ "$1" != "upgrade" ]
then
    service secureserver-agent stop || true
    for bin in $bins; do
        update-alternatives --remove "$bin" "$bin_path"/"$bin"
    done
    echo "Removing user '$user' ..."
    userdel "$user" || true

    chkconfig --del secureserver-agent
fi

exit 0
