#!/bin/sh
set -e

bin_path="/opt/secureserver-agent/embedded"
bins="secureserver-agent secureserver-config"
user="secureserver"
group="secureserver"

for bin in $bins
do
    update-alternatives --install /usr/bin/"$bin" "$bin" "$bin_path"/"$bin" 100
done

if ! getent group "$group" > /dev/null 2>&1
then
    echo "Adding new group '$group' ..."
    groupadd --system "$group"
fi

if ! id "$user" > /dev/null 2>&1
then
    echo "Adding new user '$user' with group '$group' ..."
    useradd --system --no-create-home --gid "$group" --shell /bin/false "$user"
fi

chkconfig --add secureserver-agent

if [ -n "$2" ]
then
    action=restart
else
    action=start
fi

service secureserver-agent $action 2>/dev/null || true

exit 0
