#!/bin/sh
set -e

bin_path="/opt/secureserver-agent/embedded"
bins="secureserver-agent secureserver-config"
user="secserv"
log_dir="/var/log/secureserver"
prev_version="$2"

add_system_user()
{
    if ! getent group "$user" > /dev/null 2>&1
    then
        echo "Adding new group '$user' ..."
        groupadd -r "$user"
    fi

    if ! id "$user" > /dev/null 2>&1
    then
        echo "Adding new user '$user' with group '$user' ..."
        useradd -r -M --gid "$user" --shell /bin/false "$user"
    fi
}

create_log_dir()
{
    mkdir -p "$log_dir"
    # Check if user exists
    if id -u "$user" > /dev/null 2>&1
    then
        chown "$user":"$user" "$log_dir"
    fi
}

update_alternatives()
{
    for bin in $bins
    do
        update-alternatives --install /usr/bin/"$bin" "$bin" "$bin_path"/"$bin" 100
    done
}

update_rcd()
{
    chkconfig --add secureserver-agent
}

ss_agent()
{
    service secureserver-agent "$1" 2>/dev/null || true
}

case "$1" in
    *)
        if [ -z "$prev_version" ]
        then
            add_system_user
            create_log_dir
            update_alternatives
            update_rcd
            ss_agent start
        else
            ss_agent restart
        fi
        ;;
esac
