#! /bin/sh
#
### BEGIN INIT INFO
# Provides: secureserver-agent
# Required-Start: $network $local_fs $remote_fs
# Required-Stop: $remote_fs
# Should-Start: $named
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Starts the secureserver agent.
### END INIT INFO

prog="secureserver-agent"
exec="/usr/bin/$prog"
config="/etc/secureserver/agent.config"
pidfile="/var/run/$prog.pid"
lockfile="/var/lock/subsys/$prog"
user="secserv"

# Source function library.
. /etc/init.d/functions

print_message()
{
    cat <<EOF

#####################################################################

    Before starting a secureserver-agent you need a valid api key
    in the configuration file:

        /etc/secureserver/agent.config

    You can set key by running the following command:

    secureserver-config --set api_key=REPLACE_WITH_YOUR_API_KEY

#####################################################################

EOF
}

start()
{
    # Check if api key is added
    if [ $(grep -c "REPLACE_WITH_YOUR_API_KEY" "$config") -eq 1 ]
    then
        print_message
        exit 1
    fi

    if ! [ -f $pidfile ]
    then
        printf "Starting $prog:\t"
        daemon --user=$user --pidfile=$pidfile "$exec >/dev/null &"
        # Hack to write pid
        pid=$(ps aux | grep [s]ecureserver-agent | awk '{print $2}')
        echo $pid > $pidfile
        retval=$?
        echo
        [ $retval -eq 0 ] && touch $lockfile
        return $retval
    else
        printf "$prog already running...\n"
        exit 7
    fi
}

stop()
{
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile $pidfile
    return $retval
}

restart()
{
    stop
    start
}

force_reload()
{
    restart
}

rh_status()
{
    status $prog
}

rh_status_q()
{
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    status)
        rh_status
        ;;
    restart)
        $1
        ;;
    force-reload)
        force_reload
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart|force-reload}" >&2
        exit 3
        ;;
esac
