#!/bin/sh
set -e

bin_path="/opt/secureserver-agent/embedded"
bins="secureserver-agent secureserver-config"
user="secserv"
log_dir="/var/log/secureserver"
prev_version="$2"

remove_system_user()
{
    echo "Removing user '$user' ..."
    userdel "$user" || true
}

delete_log_dir()
{
    rm -rf "$log_dir"
}

update_alternatives()
{
    for bin in $bins
    do
        update-alternatives --remove "$bin" "$bin_path"/"$bin"
    done
}

update_rcd()
{
    update-rc.d -f secureserver-agent remove > /dev/null || true
}

ss_agent()
{
    service secureserver-agent "$1" 2>/dev/null || true
}

case "$1" in
    upgrade)
        :
        ;;
    *)
        ss_agent stop
        delete_log_dir
        remove_system_user
        update_alternatives
        update_rcd
        ;;
esac
